imomi_azam/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainapp.urls', namespace='mainapp')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from.import views

app_name = 'mainapp'

urlpatterns = [
	path('',views.index, name='Home'),
	path('about/',views.about, name='About'),
	path('about/<str:sheikh_slug>',views.scholar, name='scholarDetailPage'),
	path('blog/',views.blog, name='Blog'),
	path('contact/',views.contact, name='Contact'),
	path('gallery/',views.gallery, name='gallery'),
	path('audio/',views.audio, name='audio'),
	path('blog/<str:blog_slug>',views.blog_detail, name='blogDetailPage'),
	path('ramadan/',views.ramadan, name='ramadan'),
]

mainapp/models.py
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Namaz_time(models.Model):
	name = models.CharField('Namoz nomi', max_length=100)
	time = models.CharField('Namoz vaqti', max_length=100)

	class Meta:
		verbose_name = 'Namoz vaqti'
		verbose_name_plural = 'Namoz vaqtlari'

	def __str__(self):
		return f"{self.name}"

class Blog(models.Model):
	title = models.CharField('Maqola nomi',max_length=300)
	body = RichTextField()
	slug = models.SlugField('*',max_length=100, unique=True, db_index=True)
	author = models.CharField('Muallif', default='Admin',max_length=200,blank=True)
	date = models.DateField("Qo'shilgan vaqati", auto_now_add=True)
	image = models.ImageField('Maqola rasmi', upload_to='Maqolalar_rasmi/')

	class Meta:
		verbose_name = 'Maqola'
		verbose_name_plural = 'Maqolalar'

	def get_absalute_url(self):
		return reverse('mainapp:blogDetailPage',kwargs={'blog_slug':self.slug})

	def __str__(self):
		return f'{self.title}'

class Comment(models.Model):
	blog_page = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True)
	name = models.CharField('Ismi', max_length=50)
	message = models.TextField('Xabar',)

	class  Meta:
		verbose_name = 'Muhokama'
		verbose_name_plural = 'Muhokamalar'

	def __str__(self):
		return f"{self.name}"

class Sheikhs(models.Model):
	slug = models.SlugField('*',max_length=200, unique=True, db_index=True)
	name = models.CharField('Ismi', max_length=200)
	direction = models.CharField("Yo'nalishi", max_length=200)
	fullname = models.CharField('Toliq ismi',max_length=300)
	surname = models.CharField("familiyasi",max_length=300)
	address = models.CharField('Yashash manzili',max_length=500)
	phone = models.CharField('Telfon raqami',max_length=100)
	about = models.TextField("To'liq malumoti")
	image = models.ImageField('Rasmi',upload_to='Sheikhs/')

	class Meta:
		verbose_name = 'Qori va Imom'
		verbose_name_plural = 'Qorilar va Imomlar'

	def get_absalute_url(self):
		return reverse('mainapp:scholarDetailPage',kwargs={'sheikh_slug':self.slug})
	def __str__(self):
		return f'{self.name}'

class Gallery(models.Model):
	title = models.CharField('Rasim matni',max_length=200,default='Imomi Azazm Rahmutullohi alayh jome masjid')
	date = models.DateField('Joylangan vaqti',auto_now_add=True)
	images = models.ImageField('Rasmi',upload_to='Gallerys/')

	class Meta:
		verbose_name = 'Rasim'
		verbose_name_plural = 'Rasimlar'

	def __str__(self):
		return f"{self.title}"

class Audio(models.Model):
	audio_name = models.CharField('Sura nomi',max_length=250)
	audio_img = models.ImageField(upload_to='Audio_files/')
	audio_files = models.FileField('Audioni yuklash')

	class Meta:
		verbose_name = "Audio"
		verbose_name_plural = "Audiolar"
	def __str__(self):
		return f"{self.audio_name}"

class Contact(models.Model):
	name = models.CharField("F,I,SH",max_length=250)
	email = models.EmailField('Elektron pochta',max_length=100)
	phone = models.CharField("Telfon raqami",max_length=20)
	message = models.TextField("Xabari")

	class Meta:
		verbose_name = "Aloqa"
		verbose_name_plural = "Aloqalar"
	def __str__ (self):
		return f'{self.name}'

mainapp/views.py
from django.shortcuts import render
from.models import*
from django.contrib import messages
import telebot
from django.core.paginator import Paginator

bot = telebot.TeleBot('1787606366:AAFLKfMYCWVmUSFwVDjGBLa7pU7ExcNLoqE')
my_id = -1001322633393

# Create your views here.
def index(request):
	times = Namaz_time.objects.all()
	blog = Blog.objects.all().order_by('-id')[:3]
	context = {
	'times':times,
	'blog':blog,
	}
	return render(request,'index2.html',context)

def blog(request):
	blog = Blog.objects.all().order_by("-id")
	paginator = Paginator(blog,9)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	return render(request,'blog.html',{'blog':page_obj})

def blog_detail(request,blog_slug):
	blog_page = Blog.objects.get(slug=blog_slug)
	if request.method == "POST":
		name = request.POST['name']
		message = request.POST['message']
		comment = Comment.objects.create(
			name=name,
			message=message,)
		comment.blog_page = blog_page
		comment.save()
		
		messages.add_message(request, messages.SUCCESS, "Izhohingiz qabul qilindi ")

		bot.send_message(my_id,f"Commentaryiadan xabar bor\nMaqola nomi \n  {blog_page} \nIsmi:\n  {name}  \nXabari:  \n  {message}")
	else:
		messages.add_message(request, messages.WARNING, 'Maqaola haida izohingiz bo\'lsa yozib qoldiring')

	return render(request,'blog-detail.html',{'blog_page':blog_page})

def about(request):
	sheikh = Sheikhs.objects.all()
	return render(request,'about.html',{'sheikh':sheikh})

def contact(request):
	if request.method == 'POST':
		name = request.POST['name']
		email = request.POST['email']
		phone = request.POST['phone']
		message = request.POST['message']
		Contact.objects.create(
			name=name,
			email=email,
			phone=phone,
			message=message,
			),
		messages.add_message(request, messages.SUCCESS, 'Табриклаймиз алоқа муофақиятли амалга оширилди тез орада сайит админлари сизбилан боғланишади')
		bot.send_message(my_id,f"Aloqa xizmatidan xabar bor\nIsmi:  {name}\nTelfon raqami:  {phone}\nEmail:  {email}\n Xabari:  {message}")
	return render(request,'contact.html')

def gallery(request):
	gallery = Gallery.objects.all()
	return render(request,'gallery2.html',{'gallery':gallery})

def audio(request):
	audio = Audio.objects.all().order_by("-id")
	paginator = Paginator(audio,3)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	return render(request,'audio-listening.html',{'audio':page_obj})

def scholar(request,sheikh_slug):
	sheikh = Sheikhs.objects.get(slug=sheikh_slug)
	return render(request,'scholar-detail.html',{'sheikh':sheikh})

def ramadan(request):
	return render(request,'donation-detail.html')

templates/audio-listening.html
{%extends 'base.html'%}
{%load static%}
{%block content%}
            <section>
                <div class="w-100 pt-80 black-layer pb-70 opc65 position-relative">
                    <div class="fixed-bg" style="background-image: url(https://lifeglobe.net/x/entry/2330/enlightening_by_el3sl.jpg);"></div>
                    <div class="container">
                        <div class="page-title-wrap text-center w-100">
                            <div class="page-title-inner d-inline-block">
                                <h1 class="mb-0"> АУДИО ҚУРЪОН ТИНГЛАНГ</h1>
                                <ol class="breadcrumb mb-0">
                                    <li class="breadcrumb-item"><a href="{% url 'mainapp:Home' %}" title="Home">Масжид - Бош саҳифа</a></li>
                                    <li class="breadcrumb-item active">АУДИО ҚУРЪОН </li>
                                </ol>
                            </div>
                        </div><!-- Page Title Wrap -->
                    </div>
                </div>
            </section>
            <section>
                <div class="w-100 pt-120 pb-250 position-relative">
                    <img class="sec-botm-rgt-mckp img-fluid position-absolute" src="/static/assets/images/sec-botm-mckp.png" alt="Sec Bottom Mockup">
                    <div class="container">
                        {%for audios in audio %}
                        <div class="plyr-wrp2 d-inline-block w-100">
                            <div class="plyr-box w-100 pat-bg white-layer opc85 back-blend-multiply bg-white" style="background-image: url(/static/assets/images/pattern-bg.jpg);">
                                <div class="plyr v4 w-100">
                                    <ul class="playlist mb-0 list-unstyled">
                                        <li data-cover="{{audios.audio_img.url}}"><a href="{{audios.audio_files.url}}" title="">{{audios.audio_name}}</a></li>
                                    </ul>
                                    
                                        <a class="down" href="{{audios.audio_files.url}}" title=""><i id="i" class="fas fa-download">Юклаб олиш</i></a>
                                    
                                </div>
                            </div>
                        </div><!-- Player Wrap 2 -->
                        {%endfor%}
                        <div class="pagination-wrap mt-40 d-flex flex-wrap justify-content-center text-center w-100">
                            <ul class="pagination mb-0">
                                <li class="page-item prev"><a class="page-link" href="?page=previous" title=""><i class="fas fa-long-arrow-alt-left"></i></a></li>
                                <li class="page-item "><a class="page-link" href="?page=1" title="">1</a></li>
                                <li class="page-item "><a class="page-link" href="?page=2" title="">2</a></li>
                                <li class="page-item"><a class="page-link" href="?page=3" title="">3</a></li>
                                <li class="page-item"><a class="page-link" href="?page=4" title="">4</a></li>
                                <li class="page-item"><a class="page-link" href="?page=5" title="">5</a></li>
                                <li class="page-item"><a class="page-link" href="?page=6" title="">6</a></li>
                                <li class="page-item next"><a class="page-link" href="" title=""><i class="fas fa-long-arrow-alt-right"></i></a></li>
                            </ul>
                        </div><!-- Pagination Wrap -->
                    </div>
                </div>
            </section>
{%endblock%}

templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <link rel="icon" href="{% static 'assets/images/favicon.png' %}" sizes="35x35" type="image/png">
        <title>Имоми азам жоме масжиди</title>

        <link rel="stylesheet" href="{% static 'assets/css/all.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/jquery.fancybox.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/jquery.bootstrap-touchspin.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/perfect-scrollbar.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/color.css' %}">
    </head>
    <body>
        <main>
            <div id="preloader">            
                <div class="preloader-inner">
                    <i class="preloader-icon thm-clr flaticon-kaaba"></i>
                </div>
            </div><!-- Page Loader -->
            <header class="stick style1 w-100">
                <div class="topbar bg-color1 d-flex flex-wrap justify-content-center w-100">
                    <ul class="topbar-info-list mb-0 list-unstyled d-inline-flex">
                        <li><i class="thm-clr flaticon-sun"></i>Қуёш чиқиши: <span class="thm-clr">5:05am</span></li>
                        <li><i class="thm-clr flaticon-moon"></i>Ой ботиши: <span class="thm-clr">7:14pm</span></li>
                    </ul>
                    <div class="social-links d-inline-flex">
                        <a href="https://twitter.com/" title="Twtiiter" target="_blank"><i class="fab fa-twitter"></i></a>
                        <a href="https://www.facebook.com/" title="Facebook" target="_blank"><i class="fab fa-facebook-f"></i></a>
                        <a href="https://www.youtube.com/" title="Youtube" target="_blank"><i class="fab fa-youtube"></i></a>
                        <a href="https://www.linkedin.com/" title="Linkedin" target="_blank"><i class="fab fa-linkedin-in"></i></a>
                        <a href="https://www.instagram.com/" title="Instagram" target="_blank"><i class="fab fa-instagram"></i></a>
                    </div>
                </div><!-- Topbar -->
                <div class="logo-menu-wrap d-flex flex-wrap justify-content-between w-100">
                    <span><img src="/static/assets/images/logo121.jpg" width="140" height="100" alt=""></span>    
                    <nav class="d-flex flex-wrap align-items-center justify-content-center">
                        <div class="header-left">
                            <ul class="mb-0 list-unstyled d-inline-flex">
                                <li class=""><a href="{% url 'mainapp:Home' %}" title="">Бош саҳифа</a>
                                </li>
                                <li class=""><a href="{% url 'mainapp:Blog' %}" title="">Мақолалар</a>
                                </li>
                                <li class="menu-item-has-children"><a href="javascript:void(0);" title="">Саҳифалар</a>
                                    <ul class="mb-0 list-unstyled">
                                        <li class=""><a href="{% url 'mainapp:gallery' %}" title="">Бизниг галареяларимиз</a>
                                        </li>
                                        <li><a href="{% url 'mainapp:audio' %}" title="">Аудио Қурон</a></li>
                                          <li><a href="{% url 'mainapp:ramadan' %}" title="">Рамазон Тақвими</a></li>
                                    </ul>
                                </li>
                                <li><a href="{% url 'mainapp:About' %}" title="">Масжид ҳақида</a></li>
                                <li><a href="{% url 'mainapp:Contact' %}" title="">Алоқа хизмати</a></li>

                                
                            </ul>
                        </div>
                    </nav>
                </div><!-- Logo Menu Wrap -->
            </header><!-- Header -->
            <div class="sticky-menu">
                <div class="container">
                    <div class="sticky-menu-inner d-flex flex-wrap align-items-center justify-content-between w-100">
                        <span><img src="/static/assets/images/logo121.jpg" width="140" height="100" alt=""></span> 
                        <nav class="d-flex flex-wrap align-items-center justify-content-between">
                            <div class="header-left">
                                <ul class="mb-0 list-unstyled d-inline-flex">
<li><a href="{% url 'mainapp:Home' %}" title="">Бош саҳифа</a></li> 
                                    <li class=""><a href="{% url 'mainapp:Blog' %}" title="">Мақолалар</a>
                                    </li>
                                    <li class="menu-item-has-children"><a href="javascript:void(0);" title="">Саҳифаларимиз</a>
                                        <ul class="mb-0 list-unstyled">
                                            <li class=""><a href="{% url 'mainapp:gallery' %}" title="">Бизниг галареяларимиз</a>
                                            <li><a href="{% url 'mainapp:audio' %}" title="">Аудио Қурон</a></li>
                                              <li><a href="{% url 'mainapp:ramadan' %}" title="">Рамазон Тақвими</a></li>
                                        </ul>
                                    </li>

                                    <li><a href="{% url 'mainapp:About' %}" title="">Масжид ҳақида</a></li>
                                    <li><a href="{% url 'mainapp:Contact' %}" title="">Алоқа хизмати</a></li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div><!-- Sticky Menu -->
            <div class="rspn-hdr">
                <div class="rspn-mdbr">
                    <div class="rspn-scil">
                        <a href="https://twitter.com/" title="Twtiiter" target="_blank"><i class="fab fa-twitter"></i></a>
                        <a href="https://www.facebook.com/" title="Facebook" target="_blank"><i class="fab fa-facebook-f"></i></a>
                        <a href="https://www.youtube.com/" title="Youtube" target="_blank"><i class="fab fa-youtube"></i></a>
                        <a href="https://www.linkedin.com/" title="Linkedin" target="_blank"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="lg-mn">
                    <span><img src="/static/assets/images/logo121.jpg" width="100" height="100" alt=""></span> 
                    <div class="rspn-cnt">
                        <span><i class="thm-clr far fa-envelope"></i><a href="javascript:void(0);" title="">info@youremailid.com</a></span>
                        <span><i class="thm-clr fas fa-phone-alt"></i>+96 125 554 24 5</span>
                    </div>
                    <span class="rspn-mnu-btn"><i class="fa fa-list-ul"></i></span>
                </div>
                <div class="rsnp-mnu">
                    <span class="rspn-mnu-cls"><i class="fa fa-times"></i></span>
                    <ul class="mb-0 list-unstyled w-100">
                        <li><a href="{% url 'mainapp:Home' %}" title="">Бош саҳифа</a></li> 
                        <li class=""><a href="{% url 'mainapp:Blog' %}" title="">Мақолалар</a>
                        </li>
                        <li class="menu-item-has-children"><a href="javascript:void(0);" title="">Саҳифаларимиз</a>
                            <ul class="mb-0 list-unstyled">
                            
                               
                             
                               
                                <li class=""><a href="{% url 'mainapp:gallery' %}" title="">Бизниг галареяларимиз</a>
                                </li>
                              
                                <li><a href="{% url 'mainapp:audio' %}" title="">Аудио Қурон</a></li>
                                  <li><a href="{% url 'mainapp:ramadan' %}" title="">Рамазон Тақвими</a></li>
                            </ul>
                        </li>
                    

                        <li><a href="{% url 'mainapp:About' %}" title="">Масжид ҳақида</a></li>
                        <li><a href="{% url 'mainapp:Contact' %}" title="">Алоқа хизмати</a></li> <li>
                    </ul>
                </div><!-- Responsive Menu -->
            </div><!-- Responsive Header -->






{%block content%}
{%endblock%}


           <footer style="background:#272727">
                <div class="w-100 pt-100 thm-layer pb-70 opc8 position-relative">
                    <div class="fixed-bg patern-bg back-blend-multiply thm-bg" style="background-image: url(/static/assets/images/pattern-bg.jpg);"></div>
                    <div class="container">
                        <div class="footer-data v2 w-100">
                            <div class="row">
                                <div class="col-md-12 col-sm-12 col-lg-12">
                                    <div class="widget text-center w-100">
                                        <div class="widget-inner d-inline-block">
                                            <div class="logo"><h1 class="mb-0"><a href="" title="Home">
                                             <h1 style="color:#fff">Сайт харитаси</h1>   
                                            </a></h1></div>
                                            <p class="mb-0">Ассалому алайкум Имоми азам масжидиниг веб сайит хартаснини шу ердан ҳам бошқаринг..</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4 col-sm-4 col-lg-4">
                                    <div class="widget w-100">
                                        <ul class="mb-0 list-unstyled w-100">
                                            <li><a href="{% url 'mainapp:audio' %}" title="">Аудио Қурон</a></li>
                                            <li><a href="{% url 'mainapp:Blog' %}" title="">Мақолалар</a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-md-4 col-sm-4 col-lg-4">
                                    <div class="widget w-100">
                                        <ul class="mb-0 list-unstyled w-100">
                                            <li><a href="{% url 'mainapp:About' %}" title="">Масжид ҳақида</a></li> 
                                            <li><a href="{% url 'mainapp:Home' %}" title="">Бош саҳифа</a></li> 
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-md-4 col-sm-4 col-lg-4">
                                    <div class="widget w-100">
                                        <ul class="mb-0 list-unstyled w-100">
                                            <li><a href="{% url 'mainapp:Contact' %}" title="">Алоқа хизмати</a></li>
                                            <li><a href="{% url 'mainapp:gallery' %}" title=""> Бизниг галареяларимиз</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div><!-- Footer Data -->
                        <div class="bottom-bar2 text-center w-100">
                            <p class="mb-0"><a href="{% url 'mainapp:Home' %}" title="Home">Имоми азам</a> - жоме масжиди 2021. <a href="https://themeforest.net/user/nauthemes/portfolio" title="Nauthemes" target="_blank">Арабжонов</a></p>
                        </div><!-- Bottom Bar -->
                    </div>
                </div>
            </footer><!-- Footer -->
        </main><!-- Main Wrapper -->


            <script src="{% static 'assets/js/jquery.min.js' %}"></script>
        <script src="{% static 'assets/js/popper.min.js' %}"></script>
        <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'assets/js/wow.min.js' %}"></script>
        <script src="{% static 'assets/js/counterup.min.js' %}"></script>
        <script src="{% static 'assets/js/jquery.fancybox.min.js' %}"></script>
        <script src="{% static 'assets/js/jquery.bootstrap-touchspin.min.js' %}"></script>
        <script src="{% static 'assets/js/perfect-scrollbar.min.js' %}"></script>
        <script src="{% static 'assets/js/slick.min.js' %}"></script>
        <!-- <script src="assets/js/particle-int.js"></script> -->
        <script src="{% static 'assets/js/musicplayer-min.js' %}"></script>
        <script src="{% static 'assets/js/circle-progress.min.js' %}"></script>
        <script src="{% static 'https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js' %}"></script>
        <script src="{% static 'assets/js/custom-scripts.js' %}"></script>
    </body> 
</html>

templates/page404.html
{% extends 'index.html'%}
{% block title %} Sahifa tompilmadi{% endblock %}
{% block content %}
<div class="jumbotron">
  <h1 class="display-3">Assalomu alaykum sahifa topilmadi</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for
                  calling extra attention to featured content or information.</p>
  <hr class="my-2">
  <p>It uses utility classes for typography and
     spacing to space content out within the larger container.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="{% url 'mainapp:Home' %}" role="button">Some action</a>
  </p>
</div>
{% endblock %}